#! /usr/bin/env python

from ebfilter.run import *
import argparse

parser = argparse.ArgumentParser(prog = "EBFilter")

parser.add_argument("--version", action = "version", version = "EBFilter-0.1.0")

parser.add_argument("targetMutationFile", metavar = "target.vcf", type = str,
                          help = "the path to the mutation file (vcf or annovar format)")

parser.add_argument("targetBamPath", metavar = "target.bam", type = str,
                          help = "the path to the target bam file")

parser.add_argument("controlBamPathList", metavar = "controlBam_list.txt", type = str,
                          help = "the list of paths to control bam files")

parser.add_argument("outputPath", metavar = "output.vcf", type = str,
                          help = "the path to the output")

parser.add_argument('-q', metavar = "mapping_qual_thres", default='20', type=int,
                    help = "threshold for mapping quality for calculating base counts")

parser.add_argument('-Q', metavar = "base_qual_thres", default='15', type=int,
                    help = "threshold for base quality for calculating base counts")

args = parser.parse_args()

main(args)
